### ISSUE TITLE
Unicode URI string causing NotImplementedError

### ISSUE THREAD

**Issue by swayson** [ContinuumIO/odo#211]
Hi,

You may be aware of this already. 

I am using Python  2.7.9 on Linux Mint 17.1

This works:
``` python
import blaze as bz
import pandas as pd


if __name__ == "__main__":
    bz.odo(pd.DataFrame(dict(a=[1,2,3], b=[1, 2, 3])), 'test.json')
```

But when you import the `unicode_literals` from the `__future__ package`, it raises an error:

``` python
from __future__ import (unicode_literals)
import blaze as bz
import pandas as pd


if __name__ == "__main__":
    bz.odo(pd.DataFrame(dict(a=[1,2,3], b=[1, 2, 3])), 'test.json')


Traceback (most recent call last):
  File "/home/ds/Dev/gbec_anchor_blaze/main.py", line 10, in <module>
    bz.odo(pd.DataFrame(dict(a=[1,2,3], b=[1, 2, 3])), 'test.json')
  File "/home/ds/anaconda/envs/anchor/lib/python2.7/site-packages/odo/odo.py", line 90, in odo
    return into(target, source, **kwargs)
  File "/home/ds/anaconda/envs/anchor/lib/python2.7/site-packages/multipledispatch/dispatcher.py", line 163, in __call__
    return func(*args, **kwargs)
  File "/home/ds/anaconda/envs/anchor/lib/python2.7/site-packages/odo/into.py", line 100, in into_object
    return append(target, source, **kwargs)
  File "/home/ds/anaconda/envs/anchor/lib/python2.7/site-packages/multipledispatch/dispatcher.py", line 163, in __call__
    return func(*args, **kwargs)
  File "/home/ds/anaconda/envs/anchor/lib/python2.7/site-packages/odo/append.py", line 26, in append_not_found
    "%s on to type %s" % (type(b), type(a)))
NotImplementedError: Don't know how to append datasets of type <class 'pandas.core.frame.DataFrame'> on to type <type 'unicode'>
```

**Comment by cpcloud** [comment]
Thanks for the bug report! PR coming up.
